<template>
	<div class="newslist">
		<div style="margin: auto;">
			
			<Userheader />	
			<br/><br/><br/><br/><br/>
			<div style="width: 90%;height: 60px;overflow: hidden;"></div>
			<br/>
			<!-- <div class="infinite-list" v-infinite-scroll="load" style="overflow:auto"> -->
				<Newsitem :items="items"  />
			<!-- </div> -->
			
			<br/><br/>
			<Userfooter/>
		</div>
	</div>
</template>
<script>
import Newsitem from './Newsitem.vue';
import Userheader from './Userheader.vue';
import Userfooter from './Userfooter.vue';
export default{
	name:'Newslist',
	components: { Newsitem,Userheader,Userfooter},
	mounted(){
		window.addEventListener('scroll',this.scrolling)
		this.initData()
	},
	data(){
		return {
			// animationUrl:{url:require('./static/img/3954a73634d624bcb6cc9a2ca69829f6.gif')},
			page:1,
			inputs:'',
			items:[],
			loadData:[
			{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'陆游',
					ctime:'2022.11.23',
					starts:4.5,
					title:'红酥手。黄縢酒。满城春色宫墙柳。东风恶。欢情薄。一怀愁绪，几年离索。错错错。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红酥手。黄縢酒。满城春色宫墙柳。东风恶。欢情薄。一怀愁绪，几年离索。错错错。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红酥手。黄縢酒。满城春色宫墙柳。东风恶。欢情薄。一怀愁绪，几年离索。错错错。'
						},
					]
				},
				{
					id:1,
					imgUrl:'./static/img/3.jpg',
					author:'唐婉',
					ctime:'2022.11.23',
					starts:4.5,
					title:'春如旧。人空瘦。泪痕红浥鲛绡透。桃花落。闲池阁。山盟虽在，锦书难托。莫莫莫。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'春如旧。人空瘦。泪痕红浥鲛绡透。桃花落。闲池阁。山盟虽在，锦书难托。莫莫莫。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'春如旧。人空瘦。泪痕红浥鲛绡透。桃花落。闲池阁。山盟虽在，锦书难托。莫莫莫。'
						},
					]
				},
				{
					id:1,
					imgUrl:'./static/img/1.jpg',
					author:'宋·佚名',
					ctime:'2022.11.23',
					starts:4.5,
					title:'十八新娘八十郎，苍苍白发对红妆。鸳鸯被里成双夜，一树梨花压海棠。',
					contents:[
						{
							img:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'十八新娘八十郎，苍苍白发对红妆。鸳鸯被里成双夜，一树梨花压海棠。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'十八新娘八十郎，苍苍白发对红妆。鸳鸯被里成双夜，一树梨花压海棠。'
						},
					]
				},
				{
					id:1,
					imgUrl:'./static/img/4.jpg',
					author:'你爹',
					ctime:'2022.11.23',
					starts:4.5,
					title:'我往車外看了看，說，「我買幾個橘子去。你就在此地，不要走動。」我看那邊月台的柵欄外有幾個賣東西的等著顧客。',
					contents:[
						{
							img:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'我往車外看了看，說，「我買幾個橘子去。你就在此地，不要走動。」我看那邊月台的柵欄外有幾個賣東西的等著顧客。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'我往車外看了看，說，「我買幾個橘子去。你就在此地，不要走動。」我看那邊月台的柵欄外有幾個賣東西的等著顧客。'
						},
					]
				},
			],
			testData:[
			{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'佚名',
					ctime:'2022.11.23',
					starts:2,
					title:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红尘中，谁解相思苦，只是劳燕飞，何必惹情缘。一腔痴心总错付，我为明公叹。放翁徒撩情，却是无情男。'
						},
					]
				},
				{
					id:1,
					imgUrl:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
					author:'陆游',
					ctime:'2022.11.23',
					starts:4.5,
					title:'红酥手。黄縢酒。满城春色宫墙柳。东风恶。欢情薄。一怀愁绪，几年离索。错错错。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红酥手。黄縢酒。满城春色宫墙柳。东风恶。欢情薄。一怀愁绪，几年离索。错错错。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'红酥手。黄縢酒。满城春色宫墙柳。东风恶。欢情薄。一怀愁绪，几年离索。错错错。'
						},
					]
				},
				{
					id:1,
					imgUrl:'./static/img/3.jpg',
					author:'唐婉',
					ctime:'2022.11.23',
					starts:4.5,
					title:'春如旧。人空瘦。泪痕红浥鲛绡透。桃花落。闲池阁。山盟虽在，锦书难托。莫莫莫。',
					contents:[
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'春如旧。人空瘦。泪痕红浥鲛绡透。桃花落。闲池阁。山盟虽在，锦书难托。莫莫莫。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'春如旧。人空瘦。泪痕红浥鲛绡透。桃花落。闲池阁。山盟虽在，锦书难托。莫莫莫。'
						},
					]
				},
				{
					id:1,
					imgUrl:'./static/img/1.jpg',
					author:'宋·佚名',
					ctime:'2022.11.23',
					starts:4.5,
					title:'十八新娘八十郎，苍苍白发对红妆。鸳鸯被里成双夜，一树梨花压海棠。',
					contents:[
						{
							img:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'十八新娘八十郎，苍苍白发对红妆。鸳鸯被里成双夜，一树梨花压海棠。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'十八新娘八十郎，苍苍白发对红妆。鸳鸯被里成双夜，一树梨花压海棠。'
						},
					]
				},
				{
					id:1,
					imgUrl:'./static/img/4.jpg',
					author:'你爹',
					ctime:'2022.11.23',
					starts:4.5,
					title:'我往車外看了看，說，「我買幾個橘子去。你就在此地，不要走動。」我看那邊月台的柵欄外有幾個賣東西的等著顧客。',
					contents:[
						{
							img:'https://fuss10.elemecdn.com/1/34/19aa98b1fcb2781c4fba33d850549jpeg.jpeg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'我往車外看了看，說，「我買幾個橘子去。你就在此地，不要走動。」我看那邊月台的柵欄外有幾個賣東西的等著顧客。'
						},
						{
							img:'./static/img/4.jpg',
							title:'红尘中，谁解相思苦，只是劳燕飞',
							content:'我往車外看了看，說，「我買幾個橘子去。你就在此地，不要走動。」我看那邊月台的柵欄外有幾個賣東西的等著顧客。'
						},
					]
				},
			],
			 activeIndex: '1',
        	 activeIndex2: '1'
		}
	},
	methods: {
		initData(){
			let that = this
			// console.log('chang')
			// console.log(that.loadData.length)
			// console.log('du')
			// if (that.loadData.length == 0) {that.loadData = that.testData}
			// console.log(that.loadData)
			let dataBox = that.loadData	
			that.loadData.forEach(obj => {			
				that.items.push(obj)
				// dataBox.splice(0,1)	
			});	
			console.log(that.items)
		},
		scrolling(e){
			// let current = document.documentElement.scrollTop || document.body.scrollTop;
			// let vh = window.innerHeight;
			// if(current > vh){
			// 	this.initData()
			// }else{
			// 	this.initData()
			// }
			
		},
		handleSelect(key, keyPath) {
			//console.log(key, keyPath);
		}
	}
}
</script>
<style scoped>
@media screen and (min-width: 1024px){
	.newslist{
		width: 60%;
		margin: auto;
	}
}

/* .headerp ul li:focus {

  color: red;
}
.headerp ul li:focus {
	color: blue;
} */
</style>

